server.port=8080
spring.application.name=women-day-app
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# PostgreSQL - Aiven
spring.datasource.url=jdbc:postgresql://pg-2d8918b8-daod1068-4b9a.d.aivencloud.com:26135/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Resend Email
resend.api-key=re_4oqb2Bi7_D7HPZGehJXQXUzKAREZs2sFn
resend.to-email=daod1068@gmail.com
resend.from-email=onboarding@resend.dev